spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/campus_sphere_db
    username: postgres
    password: bre_ad%4321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework: info
    org.hibernate: info

server:
  port: 8000